### ISSUE TITLE
OBS Args

### ISSUE THREAD

**Issue by cardangi** [HeavenH/heavly#7]
Acha que não vale apena tirar o argparser e colocar com sys.argv? - peso, - lib, + legibilidade do programa e funcionamento com DEF main... mas ok ;p

**Comment by Pedro-Souza** [comment]
argparser é uma lib padrão igual ao sys. Agora falar de - peso e usar import sys ?!

**Comment by cardangi** [comment]
Poderia trocar import sys para

from sys import argv.
